# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
#

exec-once = com.discordapp.Discord
exec-once = steam
exec-once = 1password
exec-once = fcitx5
