# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
#
xwayland {

force_zero_scaling = true


}

# toolkit-specific scale
env = GDK_SCALE,2
env = XCURSOR_SIZE,32
env = XCURSOR_THEME,Bibata-Modern-Classic

plugin {
	hyprfoci {
		size = 110, 0
		pos = 0, 5
		origin = 2, 0 
		imgs = /home/tea/repo/Hyprfoci/bongo
	}
}
