# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

# bindd = Ctrl+Shift, Space, 1Password ,exec, 1password --enable-features=UseOzonePlatform --ozone-platform=x11 --quick-access
# bindd = Super, G, 1Password ,exec, 1password --enable-features=UseOzonePlatform --ozone-platform=x11 --toggle
bind = Super, Tab, exec,hyprctl dispatch focusurgentorlast
bindd = ALT, TAB, Cycle to next window, cyclenext
bindd = ALT SHIFT, TAB, Cycle to prev window, cyclenext, prev
bindd = ALT, TAB, Reveal active window on top, bringactivetotop
bindd = ALT SHIFT, TAB, Reveal active window on top, bringactivetotop

bindd = Ctrl+Shift, Space, 1Password ,exec, 1password --quick-access
bindd = Ctrl+Shift, Space, 1Password ,focuswindow, initialTitle:^(.*Quick Access.*)$
bindd = Super, F1, 1Password ,exec, 1password --toggle

bindd = Super, Z, Zen Browser, exec, app.zen_browser.zen

bindd = SUPER, B, Toggle window split, togglesplit
bindd = SUPER, O, Thunderbird, exec, org.mozilla.Thunderbird
