windowrule {
  name = 1Password_Rules
  match:initial_title = Quick.*Access.*1.*assword

  pin = true
  center = true
  float = true
  no_close_for = 2000
  no_max_size = true
  stay_focused = true
  dim_around = true
  focus_on_activate = true
}
