windowrule {
  name = 1Password_Rules
  match:initial_title = Quick.*Access.*1.*assword

  pin = true
  center = true
  float = true
  no_close_for = 2000
  no_max_size = true
  stay_focused = true
  dim_around = true
  focus_on_activate = true
}

windowrule {
  name = arknight_endfield_notice_win
    match:initial_title= Form
    match:initial_class = steam_app_0

    center = true
    size = 100% 100%
    border_size = 0
}
