# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/
#
#windowrulev2 = stayfocused, title:^(Quick Access - 1Password)$
#windowrulev2 = float, title:^(Quick.*Access.*1Password)(.*)$
#windowrulev2 = stayfocused, title:^(Quick.*Access.*1Password)(.*)$
#windowrulev2 = pin, title:^(Quick Access.*1Password)(.*)$

# 1Password Quick Access Fix
# Match ANY 1Password window that isn't the main window
windowrulev2 = float, initialClass:^(1password)$, initialTitle:^(.*Quick Access.*)$
windowrulev2 = center, initialClass:^(1password)$, initialTitle:^(.*Quick Access.*)$
windowrulev2 = stayfocused, initialClass:^(1password)$, initialTitle:^(.*Quick Access.*)$
windowrulev2 = pin, initialClass:^(1password)$, initialTitle:^(.*Quick Access.*)$
windowrulev2 = dimaround, initialClass:^(1password)$, initialTitle:^(.*Quick Access.*)$
windowrulev2 = noanim, initialClass:^(1password)$, initialTitle:^(.*Quick Access.*)$
