source=~/.config/hypr/hyprlock/colors.conf

background {
    monitor =
    color = rgba(181818FF)
    path = /home/tea/Pictures/G3TXc9YbsAAZYOV.jpg
    blur_passes = 3
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $entry_border_color
    outer_color = $entry_background_color
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font Propo
    font_color = $entry_colo

    placeholder_text = Enter Password 󰈷
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 32
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
