# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays
workspace=1,monitor:DP-1,default:true
workspace=2,monitor:DP-1
workspace=3,monitor:DP-1
workspace=4,monitor:DP-1
workspace=5,monitor:DP-1
workspace=6,monitor:DP-1
workspace=7,monitor:DP-1
workspace=8,monitor:DP-1
workspace=9,monitor:DP-1
workspace=69,monitor:DP-2,default:true